"""Index isactive and businessid

Revision ID: f7461836fe0f
Revises: 
Create Date: 2025-08-22 16:39:25.309218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7461836fe0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branches')
    op.create_index(op.f('ix_branch_business_id'), 'branch', ['business_id'], unique=False)
    op.create_index(op.f('ix_branch_is_active'), 'branch', ['is_active'], unique=False)
    op.create_index(op.f('ix_business_is_active'), 'business', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_is_active'), table_name='business')
    op.drop_index(op.f('ix_branch_is_active'), table_name='branch')
    op.drop_index(op.f('ix_branch_business_id'), table_name='branch')

    # ### end Alembic commands ###
